name: Deploy EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/meu-site 2>/dev/null || cd ~
            if [ ! -d "meu-site/.git" ]; then
              git clone https://github.com/penabadluis-rgb/meu-site.git meu-site
              cd meu-site
            else
              cd meu-site
              git pull origin main
            fi
            echo "Deploy feito em $(date)"